version: '3'

services:
    web:
        image: my-laravel-image
        ports:
            - 8000:8000
        volumes:
            - ./:/app
        networks:
            - postgres-compose-network
    teste-postgres-compose:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "laravel"
        ports:
            - "15432:5432"
        volumes:
            - /home/leonardocs/postgres:/var/lib/postgresql/data
        networks:
            - postgres-compose-network

networks:
    postgres-compose-network:
        driver: bridge
