version: '3.7'

services:
    web:
        image: my-laravel-image
        ports:
            - 8000:8000
        volumes:
            - ./:/app
        networks:
            ip:
                ipv4_address: 172.16.239.10
                ipv6_address: 2001:3984:3988::10
    postgres-compose:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "laravel"
        ports:
            - "15432:5432"
        volumes:
            - /home/leonardocs/postgres:/var/lib/postgresql/data
        networks:
            ip:
                ipv4_address: 172.16.239.20
                ipv6_address: 2001:3984:3988::20

networks:
    ip:
        ipam:
            driver: default
            config:
                - subnet: 172.16.239.0/24
                - subnet: "2001:3984:3988::/64"
